#cloud-config

# Get the latest updates on initialization
package_update: true
package_upgrade: true

packages:
  - git

runcmd:
  # Install .NET SDK 9.0 (you should use the .NET Runtime)
  ## Add the Microsoft Apt Repository
  - echo "Add Microsoft repository"
  - wget https://packages.microsoft.com/config/debian/12/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - rm packages-microsoft-prod.deb

  ## Update sources
  - echo "Fethching updates"
  - apt-get update

  ## Install the .NET SDK package
  - echo "Installing the .NET SDK"
  - apt-get install -y dotnet-sdk-9.0

  # Clone the source repository
  - echo "Clonining the repository into /app/repo"
  - mkdir /app
  - git clone ${repository} /app/repo

  # Build/Publish the binary
  - echo "Building the binary"
  - cd /app/repo/src
  - dotnet publish --output /app/binary

  # Start the server
  - echo "Starting the server"
  - dotnet /app/binary/TestApi.dll # TODO! Run as background service
